name: Build

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'

jobs:
    build:
        name: Build Vencord CSS
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - uses: pnpm/action-setup@v2
              with:
                  version: latest
                  
            - name: Install jq
              uses: dcarbone/install-jq-action@v1.0.1

            - name: Install Node.js dependencies
              run: pnpm install

            - name: Compile SCSS
              run: pnpm run build
              
            - name: Get theme version
              run: echo "VERSION=$(cat manifest.json | jq '.version')" >> $GITHUB_ENV

            - name: Append Vencord metadata
              run: cd dist && echo -e "/**\n * @name Rechatty\n * @author berneseAlexxx#0001\n * @description Revival of Chatty\n * @version ${{ env.VERSION }}\n*/\n\n$(cat main.css)" > main.css

            - name: Publish artifact
              uses: actions/upload-artifact@v3
              with:
                  name: theme
                  path: dist/main.css
